{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "defaultMode": "directQuery",
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/localhost\\SP1;AdventureWorksDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "chwadeaggs.database.windows.net",
            "database": "chwadeAW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "chwadeaggs.database.windows.net;chwadeAW",
          "Username": "Jim",
          "EncryptConnection": true
        }
      }
    ],
    "tables": [
      {
        "name": "FactInternetSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "variations": [
              {
                "name": "Calendar Reuse",
                "description": "Show Calendar hierarchy as field in Internet Sales",
                "relationship": "ae49b4e7-772e-4fde-a7e4-3f5f80915766",
                "defaultHierarchy": {
                  "table": "DimDate",
                  "hierarchy": "Calendar"
                },
                "isDefault": true
              }
            ]
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate"
          },
          {
            "type": "calculated",
            "name": "Margin",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "[SalesAmount]-[TotalProductCost]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "LastUpdateDate",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdateDate"
          }
        ],
        "partitions": [
          {
            "name": "FactInternetSales",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                "in",
                "    dbo_FactInternetSales"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                  "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                  "in",
                  "    dbo_FactInternetSales</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "InternetDistinctCountSalesOrder",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])",
            "formatString": "#,0"
          },
          {
            "name": "InternetOrderLinesCount",
            "expression": "COUNTA([SalesOrderLineNumber])",
            "formatString": "#,0"
          },
          {
            "name": "InternetTotalUnits",
            "expression": "SUM([OrderQuantity])",
            "formatString": "#,0"
          },
          {
            "name": "InternetTotalDiscountAmount",
            "expression": "SUM([DiscountAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalProductCost",
            "expression": "SUM([TotalProductCost])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalSales",
            "expression": "SUM([SalesAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalTaxAmt",
            "expression": "SUM([TaxAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalFreight",
            "expression": "SUM([Freight])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalMargin",
            "expression": "SUM([Margin])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterSalesPerformance",
            "expression": "IFERROR([InternetCurrentQuarterSales]/[InternetPreviousQuarterSalesProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1.1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterSalesPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<1,-1,",
                "\t                If(x<1.07,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "1"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.07"
                }
              ]
            },
            "detailRowsDefinition": {}
          },
          {
            "name": "InternetPreviousQuarterMargin",
            "expression": "CALCULATE([InternetTotalMargin],PREVIOUSQUARTER('DimDate'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterMargin",
            "expression": "TOTALQTD([InternetTotalMargin],'DimDate'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterMarginProportionToQTD",
            "expression": "[InternetPreviousQuarterMargin]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterSales",
            "expression": "CALCULATE([InternetTotalSales],PREVIOUSQUARTER('DimDate'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterSales",
            "expression": "TOTALQTD([InternetTotalSales],'DimDate'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterSalesProportionToQTD",
            "expression": "[InternetPreviousQuarterSales]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "InternetCurrentQuarterMarginPerformance",
            "expression": "IF([InternetPreviousQuarterMarginProportionToQTD]<>0,([InternetCurrentQuarterMargin]-[InternetPreviousQuarterMarginProportionToQTD])/[InternetPreviousQuarterMarginProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1.25",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterMarginPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.8,-1,",
                "\t                If(x<1.03,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.8"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.03"
                }
              ]
            },
            "detailRowsDefinition": {}
          },
          {
            "name": "YTD InternetTotalSales",
            "expression": "CALCULATE([InternetTotalSales], DATESYTD(DimDate[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerAlternateKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternateKey"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "YearlyIncome",
            "dataType": "decimal",
            "sourceColumn": "YearlyIncome"
          },
          {
            "name": "TotalChildren",
            "dataType": "int64",
            "sourceColumn": "TotalChildren"
          },
          {
            "name": "NumberChildrenAtHome",
            "dataType": "int64",
            "sourceColumn": "NumberChildrenAtHome"
          },
          {
            "name": "EnglishEducation",
            "dataType": "string",
            "sourceColumn": "EnglishEducation"
          },
          {
            "name": "EnglishOccupation",
            "dataType": "string",
            "sourceColumn": "EnglishOccupation"
          },
          {
            "name": "HouseOwnerFlag",
            "dataType": "string",
            "sourceColumn": "HouseOwnerFlag"
          },
          {
            "name": "NumberCarsOwned",
            "dataType": "int64",
            "sourceColumn": "NumberCarsOwned"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1"
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "DateFirstPurchase",
            "dataType": "dateTime",
            "sourceColumn": "DateFirstPurchase"
          },
          {
            "name": "CommuteDistance",
            "dataType": "string",
            "sourceColumn": "CommuteDistance"
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimCustomer,{\"SpanishEducation\", \"FrenchEducation\", \"SpanishOccupation\", \"FrenchOccupation\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "showAsVariationsOnly": true,
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDateAlternateKey"
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek"
          },
          {
            "name": "EnglishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayNameOfWeek"
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear"
          },
          {
            "name": "EnglishMonthName",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName",
            "sortByColumn": "MonthNumberOfYear"
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter"
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear"
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester"
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimDate,{\"SpanishDayNameOfWeek\", \"FrenchDayNameOfWeek\", \"SpanishMonthName\", \"FrenchMonthName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "DaysCurrentQuarterToDate",
            "expression": "COUNTROWS( DATESQTD( 'DimDate'[Date])) "
          },
          {
            "name": "DaysInCurrentQuarter",
            "expression": "COUNTROWS( DATESBETWEEN( 'DimDate'[Date], STARTOFQUARTER( LASTDATE('DimDate'[Date])), ENDOFQUARTER('DimDate'[Date])))"
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "CalendarYear"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "EnglishMonthName"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          },
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "FiscalYear",
                "ordinal": 0,
                "column": "FiscalYear"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "EnglishMonthName"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode"
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode"
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost"
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel"
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture"
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine"
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style"
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName"
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "ProductSubCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductSubcategory'[EnglishProductSubcategoryName])  "
          },
          {
            "type": "calculated",
            "name": "ProductCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductCategory'[EnglishProductCategoryName]) "
          }
        ],
        "partitions": [
          {
            "name": "DimProduct",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProduct,{\"SpanishProductName\", \"FrenchProductName\", \"FrenchDescription\", \"ChineseDescription\", \"ArabicDescription\", \"HebrewDescription\", \"ThaiDescription\", \"GermanDescription\", \"JapaneseDescription\", \"TurkishDescription\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Category",
            "levels": [
              {
                "name": "Product",
                "ordinal": 3,
                "column": "EnglishProductName"
              },
              {
                "name": "Category",
                "ordinal": 0,
                "column": "ProductCategoryName"
              },
              {
                "name": "SubCategory",
                "ordinal": 1,
                "column": "ProductSubCategoryName"
              },
              {
                "name": "Model",
                "ordinal": 2,
                "column": "ModelName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "StateProvinceCode",
            "dataType": "string",
            "sourceColumn": "StateProvinceCode"
          },
          {
            "name": "StateProvince",
            "dataType": "string",
            "sourceColumn": "StateProvinceName"
          },
          {
            "name": "CountryCode",
            "dataType": "string",
            "sourceColumn": "CountryRegionCode"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "EnglishCountryRegionName"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "IpAddressLocator",
            "dataType": "string",
            "sourceColumn": "IpAddressLocator"
          }
        ],
        "partitions": [
          {
            "name": "DimGeography",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                  "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                  "in",
                  "    dbo_DimGeography</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductSubcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryAlternateKey"
          },
          {
            "name": "EnglishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          }
        ],
        "partitions": [
          {
            "name": "DimProductSubcategory",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductSubcategory,{\"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryAlternateKey"
          },
          {
            "name": "EnglishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          }
        ],
        "partitions": [
          {
            "name": "DimProductCategory",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductCategory,{\"SpanishProductCategoryName\", \"FrenchProductCategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "FactInternetSalesAgg",
        "columns": [
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "SalesAmount_Sum",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount_Sum"
          },
          {
            "name": "UnitPrice_Sum",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice_Sum"
          },
          {
            "name": "UnitPrice_Count",
            "dataType": "int64",
            "sourceColumn": "UnitPrice_Count",
            "formatString": "0"
          },
          {
            "name": "FactInternetSales_Count",
            "dataType": "int64",
            "sourceColumn": "FactInternetSales_Count",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/localhost\\SP1;AdventureWorksDW\",",
                "    dbo_FactInternetSalesAgg = Source{[Schema=\"dbo\",Item=\"FactInternetSalesAgg\"]}[Data]",
                "in",
                "    dbo_FactInternetSalesAgg"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "eac275ef-12ed-44ab-95c5-367fe2964b7a",
        "fromTable": "FactInternetSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "a5c2f953-e0a8-4f12-984a-82eba386bc31",
        "fromTable": "FactInternetSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "2f03b75d-266f-4c06-bf9a-c00a2a5fe63f",
        "fromTable": "DimCustomer",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "c3b3fe98-c83c-4340-89dc-0cdb8acba196",
        "fromTable": "DimProduct",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "fbe2a336-e918-4bc2-9765-da912e40e48b",
        "fromTable": "DimProductSubcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "DimProductCategory",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "ae49b4e7-772e-4fde-a7e4-3f5f80915766",
        "fromTable": "FactInternetSales",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "72d7695a-23c7-4841-8127-421a75135b9b",
        "fromTable": "FactInternetSalesAgg",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "b8437b63-432f-4346-ab7a-c8a3402162a6",
        "fromTable": "FactInternetSalesAgg",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "6e65c31f-3484-4301-b797-97fa8d62ebec",
        "fromTable": "FactInternetSalesAgg",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      }
    ],
    "perspectives": [
      {
        "name": "Internet Sales",
        "tables": [
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "CalendarQuarter"
              },
              {
                "name": "CalendarSemester"
              },
              {
                "name": "CalendarYear"
              },
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayNumberOfMonth"
              },
              {
                "name": "DayNumberOfWeek"
              },
              {
                "name": "DayNumberOfYear"
              },
              {
                "name": "EnglishDayNameOfWeek"
              },
              {
                "name": "EnglishMonthName"
              },
              {
                "name": "FiscalQuarter"
              },
              {
                "name": "FiscalSemester"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "MonthNumberOfYear"
              },
              {
                "name": "WeekNumberOfYear"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar"
              },
              {
                "name": "Fiscal"
              }
            ],
            "measures": [
              {
                "name": "DaysCurrentQuarterToDate"
              },
              {
                "name": "DaysInCurrentQuarter"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "City"
              },
              {
                "name": "CountryCode"
              },
              {
                "name": "Country"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "IpAddressLocator"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "StateProvinceCode"
              },
              {
                "name": "StateProvince"
              }
            ]
          },
          {
            "name": "DimProduct",
            "columns": [
              {
                "name": "Class"
              },
              {
                "name": "Color"
              },
              {
                "name": "DaysToManufacture"
              },
              {
                "name": "DealerPrice"
              },
              {
                "name": "EndDate"
              },
              {
                "name": "EnglishDescription"
              },
              {
                "name": "EnglishProductName"
              },
              {
                "name": "FinishedGoodsFlag"
              },
              {
                "name": "ListPrice"
              },
              {
                "name": "ModelName"
              },
              {
                "name": "ProductAlternateKey"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductLine"
              },
              {
                "name": "ProductSubcategoryKey"
              },
              {
                "name": "ReorderPoint"
              },
              {
                "name": "SafetyStockLevel"
              },
              {
                "name": "Size"
              },
              {
                "name": "SizeRange"
              },
              {
                "name": "SizeUnitMeasureCode"
              },
              {
                "name": "StandardCost"
              },
              {
                "name": "StartDate"
              },
              {
                "name": "Status"
              },
              {
                "name": "Style"
              },
              {
                "name": "Weight"
              },
              {
                "name": "WeightUnitMeasureCode"
              }
            ]
          },
          {
            "name": "DimProductCategory",
            "columns": [
              {
                "name": "EnglishProductCategoryName"
              },
              {
                "name": "ProductCategoryAlternateKey"
              },
              {
                "name": "ProductCategoryKey"
              }
            ]
          },
          {
            "name": "DimProductSubcategory",
            "columns": [
              {
                "name": "EnglishProductSubcategoryName"
              },
              {
                "name": "ProductCategoryKey"
              },
              {
                "name": "ProductSubcategoryAlternateKey"
              },
              {
                "name": "ProductSubcategoryKey"
              }
            ]
          },
          {
            "name": "FactInternetSales",
            "columns": [
              {
                "name": "CarrierTrackingNumber"
              },
              {
                "name": "CurrencyKey"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "CustomerPONumber"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "DueDate"
              },
              {
                "name": "DueDateKey"
              },
              {
                "name": "ExtendedAmount"
              },
              {
                "name": "Freight"
              },
              {
                "name": "Margin"
              },
              {
                "name": "OrderDate"
              },
              {
                "name": "OrderDateKey"
              },
              {
                "name": "OrderQuantity"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductStandardCost"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "RevisionNumber"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "SalesOrderLineNumber"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "ShipDate"
              },
              {
                "name": "ShipDateKey"
              },
              {
                "name": "TaxAmt"
              },
              {
                "name": "TotalProductCost"
              },
              {
                "name": "UnitPrice"
              },
              {
                "name": "UnitPriceDiscountPct"
              }
            ],
            "measures": [
              {
                "name": "InternetCurrentQuarterMargin"
              },
              {
                "name": "InternetCurrentQuarterSales"
              },
              {
                "name": "InternetDistinctCountSalesOrder"
              },
              {
                "name": "InternetOrderLinesCount"
              },
              {
                "name": "InternetPreviousQuarterMargin"
              },
              {
                "name": "InternetPreviousQuarterMarginProportionToQTD"
              },
              {
                "name": "InternetPreviousQuarterSales"
              },
              {
                "name": "InternetPreviousQuarterSalesProportionToQTD"
              },
              {
                "name": "InternetTotalDiscountAmount"
              },
              {
                "name": "InternetTotalFreight"
              },
              {
                "name": "InternetTotalMargin"
              },
              {
                "name": "InternetTotalProductCost"
              },
              {
                "name": "InternetTotalSales"
              },
              {
                "name": "InternetTotalTaxAmt"
              },
              {
                "name": "InternetTotalUnits"
              },
              {
                "name": "InternetCurrentQuarterMarginPerformance"
              },
              {
                "name": "InternetCurrentQuarterSalesPerformance"
              }
            ]
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "RangeStart",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #datetime(2013, 6, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ]
      },
      {
        "name": "RangeEnd",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #datetime(2013, 6, 8, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}