{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "AdventureWorks",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost\\SP1",
            "database": "AdventureWorksDW"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "kind": "SQL",
          "path": "localhost\\sp1",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Internet Sales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "variations": [
              {
                "name": "Calendar Reuse",
                "description": "Show Calendar hierarchy as field in Internet Sales",
                "relationship": "ae49b4e7-772e-4fde-a7e4-3f5f80915766",
                "defaultHierarchy": {
                  "table": "Date",
                  "hierarchy": "Calendar"
                },
                "isDefault": true
              }
            ]
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate"
          },
          {
            "type": "calculated",
            "name": "Margin",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "[SalesAmount]-[TotalProductCost]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Internet Sales",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                "in",
                "    dbo_FactInternetSales"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"AdventureWorks\",",
                  "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                  "in",
                  "    dbo_FactInternetSales</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "InternetDistinctCountSalesOrder",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])",
            "formatString": "#,0",
            "detailRowsDefinition": {}
          },
          {
            "name": "InternetOrderLinesCount",
            "expression": "COUNTA([SalesOrderLineNumber])",
            "formatString": "#,0",
            "detailRowsDefinition": {}
          },
          {
            "name": "InternetTotalUnits",
            "expression": "SUM([OrderQuantity])",
            "formatString": "#,0",
            "detailRowsDefinition": {}
          },
          {
            "name": "InternetTotalDiscountAmount",
            "expression": "SUM([DiscountAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalProductCost",
            "expression": "SUM([TotalProductCost])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalSales",
            "expression": "SUM([SalesAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalTaxAmt",
            "expression": "SUM([TaxAmt])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalFreight",
            "expression": "SUM([Freight])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalMargin",
            "expression": "SUM([Margin])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterSalesPerformance",
            "expression": "IFERROR([InternetCurrentQuarterSales]/[InternetPreviousQuarterSalesProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1.1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='Internet Sales'[InternetCurrentQuarterSalesPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<1,-1,",
                "\t                If(x<1.07,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "1"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.07"
                }
              ]
            },
            "detailRowsDefinition": {}
          },
          {
            "name": "InternetPreviousQuarterMargin",
            "expression": "CALCULATE([InternetTotalMargin],PREVIOUSQUARTER('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterMargin",
            "expression": "TOTALQTD([InternetTotalMargin],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterMarginProportionToQTD",
            "expression": "[InternetPreviousQuarterMargin]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterSales",
            "expression": "CALCULATE([InternetTotalSales],PREVIOUSQUARTER('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterSales",
            "expression": "TOTALQTD([InternetTotalSales],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterSalesProportionToQTD",
            "expression": "[InternetPreviousQuarterSales]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetCurrentQuarterMarginPerformance",
            "expression": "IF([InternetPreviousQuarterMarginProportionToQTD]<>0,([InternetCurrentQuarterMargin]-[InternetPreviousQuarterMarginProportionToQTD])/[InternetPreviousQuarterMarginProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1.25",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='Internet Sales'[InternetCurrentQuarterMarginPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.8,-1,",
                "\t                If(x<1.03,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.8"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.03"
                }
              ]
            },
            "detailRowsDefinition": {}
          },
          {
            "name": "YTD InternetTotalSales",
            "expression": "CALCULATE([InternetTotalSales], DATESYTD('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerAlternateKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternateKey"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "YearlyIncome",
            "dataType": "decimal",
            "sourceColumn": "YearlyIncome"
          },
          {
            "name": "TotalChildren",
            "dataType": "int64",
            "sourceColumn": "TotalChildren"
          },
          {
            "name": "NumberChildrenAtHome",
            "dataType": "int64",
            "sourceColumn": "NumberChildrenAtHome"
          },
          {
            "name": "EnglishEducation",
            "dataType": "string",
            "sourceColumn": "EnglishEducation"
          },
          {
            "name": "EnglishOccupation",
            "dataType": "string",
            "sourceColumn": "EnglishOccupation"
          },
          {
            "name": "HouseOwnerFlag",
            "dataType": "string",
            "sourceColumn": "HouseOwnerFlag"
          },
          {
            "name": "NumberCarsOwned",
            "dataType": "int64",
            "sourceColumn": "NumberCarsOwned"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1"
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "DateFirstPurchase",
            "dataType": "dateTime",
            "sourceColumn": "DateFirstPurchase"
          },
          {
            "name": "CommuteDistance",
            "dataType": "string",
            "sourceColumn": "CommuteDistance"
          }
        ],
        "partitions": [
          {
            "name": "DimCustomer",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimCustomer,{\"SpanishEducation\", \"FrenchEducation\", \"SpanishOccupation\", \"FrenchOccupation\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Date",
        "showAsVariationsOnly": true,
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDateAlternateKey"
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek"
          },
          {
            "name": "EnglishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayNameOfWeek"
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear"
          },
          {
            "name": "EnglishMonthName",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName",
            "sortByColumn": "MonthNumberOfYear"
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter"
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear"
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester"
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimDate,{\"SpanishDayNameOfWeek\", \"FrenchDayNameOfWeek\", \"SpanishMonthName\", \"FrenchMonthName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "DaysCurrentQuarterToDate",
            "expression": "COUNTROWS( DATESQTD( 'Date'[Date])) ",
            "detailRowsDefinition": {}
          },
          {
            "name": "DaysInCurrentQuarter",
            "expression": "COUNTROWS( DATESBETWEEN( 'Date'[Date], STARTOFQUARTER( LASTDATE('Date'[Date])), ENDOFQUARTER('Date'[Date])))",
            "detailRowsDefinition": {}
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "CalendarYear"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "EnglishMonthName"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          },
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "FiscalYear",
                "ordinal": 0,
                "column": "FiscalYear"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "EnglishMonthName"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode"
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode"
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost"
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel"
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture"
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine"
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style"
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName"
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "ProductSubCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('Product Subcategory'[EnglishProductSubcategoryName])  "
          },
          {
            "type": "calculated",
            "name": "ProductCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('Product Category'[EnglishProductCategoryName]) "
          }
        ],
        "partitions": [
          {
            "name": "DimProduct",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProduct,{\"SpanishProductName\", \"FrenchProductName\", \"FrenchDescription\", \"ChineseDescription\", \"ArabicDescription\", \"HebrewDescription\", \"ThaiDescription\", \"GermanDescription\", \"JapaneseDescription\", \"TurkishDescription\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Category",
            "levels": [
              {
                "name": "Product",
                "ordinal": 3,
                "column": "EnglishProductName"
              },
              {
                "name": "Category",
                "ordinal": 0,
                "column": "ProductCategoryName"
              },
              {
                "name": "SubCategory",
                "ordinal": 1,
                "column": "ProductSubCategoryName"
              },
              {
                "name": "Model",
                "ordinal": 2,
                "column": "ModelName"
              }
            ]
          }
        ]
      },
      {
        "name": "Geography",
        "columns": [
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "StateProvinceCode",
            "dataType": "string",
            "sourceColumn": "StateProvinceCode"
          },
          {
            "name": "StateProvince",
            "dataType": "string",
            "sourceColumn": "StateProvinceName"
          },
          {
            "name": "CountryCode",
            "dataType": "string",
            "sourceColumn": "CountryRegionCode"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "EnglishCountryRegionName"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "IpAddressLocator",
            "dataType": "string",
            "sourceColumn": "IpAddressLocator"
          }
        ],
        "partitions": [
          {
            "name": "DimGeography",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"AdventureWorks\",",
                  "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                  "in",
                  "    dbo_DimGeography</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Product Subcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryAlternateKey"
          },
          {
            "name": "EnglishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          }
        ],
        "partitions": [
          {
            "name": "DimProductSubcategory",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductSubcategory,{\"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Product Category",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryAlternateKey"
          },
          {
            "name": "EnglishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          }
        ],
        "partitions": [
          {
            "name": "DimProductCategory",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductCategory,{\"SpanishProductCategoryName\", \"FrenchProductCategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Reseller Sales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "ResellerKey",
            "dataType": "int64",
            "sourceColumn": "ResellerKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate"
          },
          {
            "name": "DueDate",
            "dataType": "dateTime",
            "sourceColumn": "DueDate"
          },
          {
            "name": "ShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ShipDate"
          }
        ],
        "partitions": [
          {
            "name": "Reseller Sales",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_FactResellerSales = Source{[Schema=\"dbo\",Item=\"FactResellerSales\"]}[Data]",
                "in",
                "    dbo_FactResellerSales"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"AdventureWorks\",",
                  "    dbo_FactResellerSales = Source{[Schema=\"dbo\",Item=\"FactResellerSales\"]}[Data]",
                  "in",
                  "    dbo_FactResellerSales</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "ResellerTotalSales",
            "expression": "SUM([SalesAmount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "detailRowsDefinition": {},
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "Employee",
        "columns": [
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "ParentEmployeeKey",
            "dataType": "int64",
            "sourceColumn": "ParentEmployeeKey"
          },
          {
            "name": "EmployeeNationalIDAlternateKey",
            "dataType": "string",
            "sourceColumn": "EmployeeNationalIDAlternateKey"
          },
          {
            "name": "ParentEmployeeNationalIDAlternateKey",
            "dataType": "string",
            "sourceColumn": "ParentEmployeeNationalIDAlternateKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "HireDate",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "LoginID",
            "dataType": "string",
            "sourceColumn": "LoginID"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "EmergencyContactName",
            "dataType": "string",
            "sourceColumn": "EmergencyContactName"
          },
          {
            "name": "EmergencyContactPhone",
            "dataType": "string",
            "sourceColumn": "EmergencyContactPhone"
          },
          {
            "name": "SalariedFlag",
            "dataType": "boolean",
            "sourceColumn": "SalariedFlag"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "PayFrequency",
            "dataType": "int64",
            "sourceColumn": "PayFrequency"
          },
          {
            "name": "BaseRate",
            "dataType": "decimal",
            "sourceColumn": "BaseRate"
          },
          {
            "name": "VacationHours",
            "dataType": "int64",
            "sourceColumn": "VacationHours"
          },
          {
            "name": "SickLeaveHours",
            "dataType": "int64",
            "sourceColumn": "SickLeaveHours"
          },
          {
            "name": "CurrentFlag",
            "dataType": "boolean",
            "sourceColumn": "CurrentFlag"
          },
          {
            "name": "SalesPersonFlag",
            "dataType": "boolean",
            "sourceColumn": "SalesPersonFlag"
          },
          {
            "name": "DepartmentName",
            "dataType": "string",
            "sourceColumn": "DepartmentName"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "FullName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "[FirstName] & \" \" & [MiddleName] & \" \" & [LastName]"
          },
          {
            "type": "calculated",
            "name": "Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "PATH([EmployeeKey],[ParentEmployeeKey])"
          },
          {
            "type": "calculated",
            "name": "Level1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(Employee[FullName],Employee[EmployeeKey],PATHITEM([Path],1,1))"
          },
          {
            "type": "calculated",
            "name": "Level2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "LOOKUPVALUE(",
              "  Employee[FullName],",
              "  Employee[EmployeeKey],",
              "  PATHITEM([Path],2,1)",
              ")"
            ]
          },
          {
            "type": "calculated",
            "name": "Level3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(Employee[FullName],Employee[EmployeeKey],PATHITEM([Path],3,1))"
          },
          {
            "type": "calculated",
            "name": "Level4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(Employee[FullName],Employee[EmployeeKey],PATHITEM([Path],4,1))"
          },
          {
            "type": "calculated",
            "name": "Level5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(Employee[FullName],Employee[EmployeeKey],PATHITEM([Path],5,1))"
          }
        ],
        "partitions": [
          {
            "name": "DimEmployee",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"AdventureWorks\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Organization",
            "levels": [
              {
                "name": "Level1",
                "ordinal": 0,
                "column": "Level1"
              },
              {
                "name": "Level2",
                "ordinal": 1,
                "column": "Level2"
              },
              {
                "name": "Level3",
                "ordinal": 2,
                "column": "Level3"
              },
              {
                "name": "Level4",
                "ordinal": 3,
                "column": "Level4"
              },
              {
                "name": "Level5",
                "ordinal": 4,
                "column": "Level5"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "eac275ef-12ed-44ab-95c5-367fe2964b7a",
        "fromTable": "Internet Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "a5c2f953-e0a8-4f12-984a-82eba386bc31",
        "fromTable": "Internet Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "2f03b75d-266f-4c06-bf9a-c00a2a5fe63f",
        "fromTable": "Customer",
        "fromColumn": "GeographyKey",
        "toTable": "Geography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "c3b3fe98-c83c-4340-89dc-0cdb8acba196",
        "fromTable": "Product",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "Product Subcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "fbe2a336-e918-4bc2-9765-da912e40e48b",
        "fromTable": "Product Subcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "Product Category",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "1f7402f3-4ec1-4916-b766-dbdee2711bfd",
        "fromTable": "Reseller Sales",
        "fromColumn": "EmployeeKey",
        "toTable": "Employee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "38811126-0c3f-47dd-9c7c-c271da105e10",
        "fromTable": "Reseller Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "7ee649d8-b06b-4965-90e1-f9244173b3d9",
        "fromTable": "Reseller Sales",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey"
      },
      {
        "name": "e7a1ad50-9554-4041-a9c9-9075f09ebe90",
        "fromTable": "Reseller Sales",
        "fromColumn": "DueDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "1e5d554f-ea4a-4b43-9ab7-3029e8cbe953",
        "fromTable": "Reseller Sales",
        "fromColumn": "ShipDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "9f36b1bc-0fae-4f03-94a9-b6996acf96f6",
        "fromTable": "Internet Sales",
        "fromColumn": "DueDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "6e3e2bb9-d63c-4f1b-a65a-0a1a82dfbf75",
        "fromTable": "Internet Sales",
        "fromColumn": "ShipDateKey",
        "toTable": "Date",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "ae49b4e7-772e-4fde-a7e4-3f5f80915766",
        "fromTable": "Internet Sales",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey"
      }
    ],
    "perspectives": [
      {
        "name": "Internet Sales",
        "tables": [
          {
            "name": "Date",
            "columns": [
              {
                "name": "CalendarQuarter"
              },
              {
                "name": "CalendarSemester"
              },
              {
                "name": "CalendarYear"
              },
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayNumberOfMonth"
              },
              {
                "name": "DayNumberOfWeek"
              },
              {
                "name": "DayNumberOfYear"
              },
              {
                "name": "EnglishDayNameOfWeek"
              },
              {
                "name": "EnglishMonthName"
              },
              {
                "name": "FiscalQuarter"
              },
              {
                "name": "FiscalSemester"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "MonthNumberOfYear"
              },
              {
                "name": "WeekNumberOfYear"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar"
              },
              {
                "name": "Fiscal"
              }
            ],
            "measures": [
              {
                "name": "DaysCurrentQuarterToDate"
              },
              {
                "name": "DaysInCurrentQuarter"
              }
            ]
          },
          {
            "name": "Geography",
            "columns": [
              {
                "name": "City"
              },
              {
                "name": "CountryCode"
              },
              {
                "name": "Country"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "IpAddressLocator"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "StateProvinceCode"
              },
              {
                "name": "StateProvince"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "Class"
              },
              {
                "name": "Color"
              },
              {
                "name": "DaysToManufacture"
              },
              {
                "name": "DealerPrice"
              },
              {
                "name": "EndDate"
              },
              {
                "name": "EnglishDescription"
              },
              {
                "name": "EnglishProductName"
              },
              {
                "name": "FinishedGoodsFlag"
              },
              {
                "name": "ListPrice"
              },
              {
                "name": "ModelName"
              },
              {
                "name": "ProductAlternateKey"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductLine"
              },
              {
                "name": "ProductSubcategoryKey"
              },
              {
                "name": "ReorderPoint"
              },
              {
                "name": "SafetyStockLevel"
              },
              {
                "name": "Size"
              },
              {
                "name": "SizeRange"
              },
              {
                "name": "SizeUnitMeasureCode"
              },
              {
                "name": "StandardCost"
              },
              {
                "name": "StartDate"
              },
              {
                "name": "Status"
              },
              {
                "name": "Style"
              },
              {
                "name": "Weight"
              },
              {
                "name": "WeightUnitMeasureCode"
              }
            ]
          },
          {
            "name": "Product Category",
            "columns": [
              {
                "name": "EnglishProductCategoryName"
              },
              {
                "name": "ProductCategoryAlternateKey"
              },
              {
                "name": "ProductCategoryKey"
              }
            ]
          },
          {
            "name": "Product Subcategory",
            "columns": [
              {
                "name": "EnglishProductSubcategoryName"
              },
              {
                "name": "ProductCategoryKey"
              },
              {
                "name": "ProductSubcategoryAlternateKey"
              },
              {
                "name": "ProductSubcategoryKey"
              }
            ]
          },
          {
            "name": "Internet Sales",
            "columns": [
              {
                "name": "CarrierTrackingNumber"
              },
              {
                "name": "CurrencyKey"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "CustomerPONumber"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "DueDate"
              },
              {
                "name": "DueDateKey"
              },
              {
                "name": "ExtendedAmount"
              },
              {
                "name": "Freight"
              },
              {
                "name": "Margin"
              },
              {
                "name": "OrderDate"
              },
              {
                "name": "OrderDateKey"
              },
              {
                "name": "OrderQuantity"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductStandardCost"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "RevisionNumber"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "SalesOrderLineNumber"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "ShipDate"
              },
              {
                "name": "ShipDateKey"
              },
              {
                "name": "TaxAmt"
              },
              {
                "name": "TotalProductCost"
              },
              {
                "name": "UnitPrice"
              },
              {
                "name": "UnitPriceDiscountPct"
              }
            ],
            "measures": [
              {
                "name": "InternetCurrentQuarterMargin"
              },
              {
                "name": "InternetCurrentQuarterSales"
              },
              {
                "name": "InternetDistinctCountSalesOrder"
              },
              {
                "name": "InternetOrderLinesCount"
              },
              {
                "name": "InternetPreviousQuarterMargin"
              },
              {
                "name": "InternetPreviousQuarterMarginProportionToQTD"
              },
              {
                "name": "InternetPreviousQuarterSales"
              },
              {
                "name": "InternetPreviousQuarterSalesProportionToQTD"
              },
              {
                "name": "InternetTotalDiscountAmount"
              },
              {
                "name": "InternetTotalFreight"
              },
              {
                "name": "InternetTotalMargin"
              },
              {
                "name": "InternetTotalProductCost"
              },
              {
                "name": "InternetTotalSales"
              },
              {
                "name": "InternetTotalTaxAmt"
              },
              {
                "name": "InternetTotalUnits"
              },
              {
                "name": "InternetCurrentQuarterMarginPerformance"
              },
              {
                "name": "InternetCurrentQuarterSalesPerformance"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "General Users",
        "description": "Readers of the model",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "kayu@microsoft.com",
            "memberId": "kayu@microsoft.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "bretgr@microsoft.com",
            "memberId": "bretgr@microsoft.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jocaplan@microsoft.com",
            "memberId": "jocaplan@microsoft.com",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "Geography",
            "filterExpression": "Geography[CountryCode]=\"US\""
          },
          {
            "name": "Customer",
            "columnPermissions": [
              {
                "name": "Phone",
                "metadataPermission": "none"
              }
            ]
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}