//Todo2: delete file


////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.18052
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace BismNormalizer {
    
    
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
//    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
//        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
//        public static Settings Default {
//            get {
//                return defaultInstance;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("localhost|")]
//        public string TargetServerAutoCompleteEntries {
//            get {
//                return ((string)(this["TargetServerAutoCompleteEntries"]));
//            }
//            set {
//                this["TargetServerAutoCompleteEntries"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string TargetCatalog {
//            get {
//                return ((string)(this["TargetCatalog"]));
//            }
//            set {
//                this["TargetCatalog"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("localhost|")]
//        public string SourceServerAutoCompleteEntries {
//            get {
//                return ((string)(this["SourceServerAutoCompleteEntries"]));
//            }
//            set {
//                this["SourceServerAutoCompleteEntries"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("")]
//        public string SourceCatalog {
//            get {
//                return ((string)(this["SourceCatalog"]));
//            }
//            set {
//                this["SourceCatalog"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool InformationalMessagesVisible {
//            get {
//                return ((bool)(this["InformationalMessagesVisible"]));
//            }
//            set {
//                this["InformationalMessagesVisible"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool WarningsVisible {
//            get {
//                return ((bool)(this["WarningsVisible"]));
//            }
//            set {
//                this["WarningsVisible"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool ToolbarVisible {
//            get {
//                return ((bool)(this["ToolbarVisible"]));
//            }
//            set {
//                this["ToolbarVisible"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionRoles {
//            get {
//                return ((bool)(this["OptionRoles"]));
//            }
//            set {
//                this["OptionRoles"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionPartitions {
//            get {
//                return ((bool)(this["OptionPartitions"]));
//            }
//            set {
//                this["OptionPartitions"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool OptionMeasureDependencies {
//            get {
//                return ((bool)(this["OptionMeasureDependencies"]));
//            }
//            set {
//                this["OptionMeasureDependencies"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionPerspectives {
//            get {
//                return ((bool)(this["OptionPerspectives"]));
//            }
//            set {
//                this["OptionPerspectives"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("True")]
//        public bool OptionMergePerspectives {
//            get {
//                return ((bool)(this["OptionMergePerspectives"]));
//            }
//            set {
//                this["OptionMergePerspectives"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionDisplayFolders {
//            get {
//                return ((bool)(this["OptionDisplayFolders"]));
//            }
//            set {
//                this["OptionDisplayFolders"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionActions {
//            get {
//                return ((bool)(this["OptionActions"]));
//            }
//            set {
//                this["OptionActions"] = value;
//            }
//        }
        
//        [global::System.Configuration.UserScopedSettingAttribute()]
//        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//        [global::System.Configuration.DefaultSettingValueAttribute("False")]
//        public bool OptionTranslations {
//            get {
//                return ((bool)(this["OptionTranslations"]));
//            }
//            set {
//                this["OptionTranslations"] = value;
//            }
//        }
//    }
//}
